pool:
  default

variables:
  JDKVersion: '19.0.1'

steps:
- task: PowerShell@2
  displayName: 'Print Java environment variables'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "JAVA_HOME:" $env:JAVA_HOME
      Write-Host "PATH:" $env:PATH

- task: Gradle@2
  inputs:
    workingDirectory: '/startUp2'
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: 'default'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '/TEST-*.xml'
    tasks: 'build'
