trigger:
- main

pool:
  name: Default

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '19'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'LocalDirectory'
    jdkFile: 'C:\agent\openjdk-19.0.1-1.zip'
    jdkDestinationDirectory: 'C:\agent\openjdk-19.0.1-1'
    cleanDestinationDirectory: true
    createExtractDirectory: false

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'startUp2/gradlew.bat'
    workingDirectory: 'startUp2'
    tasks: 'build'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false

- task: SSH@0
  inputs:
    sshEndpoint: 'ssh_myvm'
    runOptions: 'commands'
    commands: 'echo "Hello from Azurevm"'
    readyTimeout: '20000'
