trigger:
- main

pool:
  name: Default

steps:
- task: Gradle@2
  inputs:
    workingDirectory: '/startUp2'
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.7'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'

- task: SSH@0
  inputs:
    sshEndpoint: 'ssh_myvm'
    runOptions: 'commands'
    commands: 'echo "Hello from Azurevm"'
    readyTimeout: '20000'
