trigger:
- main

pool:
  name: Default

jobs:
- job: build
  steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '19'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'LocalDirectory'
      jdkFile: 'C:\agent\openjdk-19.0.1-1.zip'
      jdkDestinationDirectory: 'C:\agent\openjdk-19.0.1-1'
      cleanDestinationDirectory: true
      createExtractDirectory: false

  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'startUp2/gradlew.bat'
      workingDirectory: 'startUp2'
      tasks: 'build' # Removed 'clean' for speed unless needed for each build
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      sonarQubeRunAnalysis: false
      spotBugsAnalysis: false

  - task: CopyFiles@2
    displayName: 'Copy JAR to artifact staging directory'
    inputs:
      SourceFolder: 'startUp2/build/libs'  # Adjusted source folder
      Contents: '*.jar'
      TargetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishPipelineArtifact@1 # Use the correct task for publishing
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory) 
      artifactName: 'drop'

- deployment: Java
  dependsOn: build
  pool:
    name: 'default'
  environment: azurevm
  strategy:
    runOnce:
      preDeploy:
        steps:
        - download: current
          artifact: drop
        # ...  (other steps)

      deploy:
        steps:    
        - task: SSH@0
          inputs:
            sshEndpoint: 'ssh_myvm'
            runOptions: 'commands'
            commands: |
              sudo mkdir -p /var/www/myapp

        - task: CopyFilesOverSSH@0
          inputs:
            sshEndpoint: 'ssh_myvm'
            sourceFolder: '$(Pipeline.Workspace)/drop'  # Download location
            contents: '*.jar' 
            targetFolder: '/home/azureuser'

        - task: SSH@0
          inputs:
            sshEndpoint: 'ssh_myvm'
            runOptions: 'inline'
            inline: |
              echo "Starting deployment script run"
              # Use full path to ensure Java is found
              java -jar '/home/azureuser/app1-1.0-SNAPSHOT.jar'