trigger:
- main

pool:
  name: Default

jobs:
- job: build
  steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '19'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'LocalDirectory'
      jdkFile: 'C:\agent\openjdk-19.0.1-1.zip'
      jdkDestinationDirectory: 'C:\agent\openjdk-19.0.1-1'
      cleanDestinationDirectory: true
      createExtractDirectory: false

  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'startUp2/gradlew.bat'
      workingDirectory: 'startUp2'
      tasks: 'clean build'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      sonarQubeRunAnalysis: false
      spotBugsAnalysis: false
  - task: CopyFiles@2
    displayName: 'Copy Files to artifact staging directory'
    inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)
  - upload: $(Build.ArtifactStagingDirectory)
    artifact: drop


  # # Publish artifact
  # - task: PublishBuildArtifacts@1
  #   inputs:
  #     pathToPublish: '$(Pipeline.Workspace)/s/startUp2/build/libs/'
  #     artifactName: 'drop'
  # - task: PublishBuildArtifacts@1
  #   inputs:
  #     pathToPublish: '$(Pipeline.Workspace)/s/startUp2/deploy.sh'
  #     artifactName: 'script'


- deployment: Java
  dependsOn: build
  pool:
    name: 'default'
  environment: azurevm
  strategy:
    runOnce:
      deploy:
          steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Modify deployment script based on the app type
                echo "Starting deployment script run"
                sudo java -jar '$(Pipeline.Workspace)/drop/**/target/*.jar'

        # - task: DownloadBuildArtifacts@0
        #   inputs:
        #     artifactName: 'drop' 
        #     downloadPath: '$(System.DefaultWorkingDirectory)/myapp'
        # - task: DownloadBuildArtifacts@0
        #   inputs:
        #     artifactName: 'script' 
        #     downloadPath: '$(System.DefaultWorkingDirectory)/myapp'

        # - task: SSH@0
        #   inputs:
        #     sshEndpoint: 'ssh_myvm'
        #     runOptions: 'inline'
        #     inline: |
        #       sudo java -jar $(System.DefaultWorkingDirectory)/target/app1-0.0.1-SNAPSHOT-plain.jar

        # - task: SSH@0
        #   inputs:
        #     sshEndpoint: 'ssh_myvm'
        #     runOptions: 'commands'
        #     commands: |
        #       sudo mkdir -p /var/www/myapp

        # - task: CopyFilesOverSSH@0
        #   inputs:
        #     sshEndpoint: 'ssh_myvm'
        #     sourceFolder: '$(Pipeline.Workspace)/myapp'
        #     contents: '**/*'
        #     targetFolder: 'azureuser@52.191.77.169:/var/www/myapp'
        #     readyTimeout: '20000'

        # - task: SSH@0
        #   inputs:
        #     sshEndpoint: 'ssh_myvm'
        #     runOptions: 'script'
        #     scriptPath: '$(Pipeline.Workspace)/s/startUp2/deploy.sh'
        #     readyTimeout: '20000'