trigger:
- main

pool:
  name: Default

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: $(JDKVersion)
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: Gradle@2
  inputs:
    workingDirectory: 'C:\Program Files\learn-spring-framework\startUp2'
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: 'default'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'

- task: SSH@0
  inputs:
    sshEndpoint: 'ssh_myvm'
    runOptions: 'commands'
    commands: 'echo "Hello from Azurevm"'
    readyTimeout: '20000'
